# Generated by Django 4.2.7 on 2023-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=225)),
                ("no_of_guests", models.IntegerField()),
                ("BookingDate", models.DateTimeField()),
            ],
            options={"db_table": "booking",},
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.PositiveIntegerField()),
            ],
            options={"db_table": "menu",},
        ),
    ]
